#!/bin/bash

# Launches a local docker container that will have a PSQL DB on it.
# Note, it takes a few seconds for database to initialize after running
# this script. Once initializated then 'run_flyway' can be run to install
# schema and tables.
# TODO: I'm not sure that the DB takes a few seconds to initialize anymore.

../gradlew startContainer
